removes linearmor and PA block
f13nametbd/f13tbd pull request #20
Opened 2023-11-11 10:08 UTC by lolman360

## About The Pull Request

tin

## Why It's Good For The Game

LINEARMOR'S SKELETAL REMNANTS ARE GONE

PA GIVING YOU A 70% CHANCE TO DEFLECT BULLETS THAT DO LESS THAN 18 DAMAGE REGARDLESS OF AP is not a good thing

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
del: the last vestiges of linearmor from the code
balance: PA no longer has a 70% chance to deflect sub-18 damage bullets
/:cl:

2023-11-11 12:54 UTC, lolman360 commented on code/modules/clothing/head/f13head.dm
> -/obj/item/clothing/head/helmet/f13/power_armor/run_block(mob/living/owner, atom/object, damage, attack_text, attack_type, armour_penetration, mob/attacker, def_zone, final_block_chance, list/block_re
if ESD, the `hard counter` to PA is overperforming then... nerf ESD, don't buff PA

ESD is mostly too cheap atm. the available weapons for it are fine (.22 and 5mm) imo but that's an issue for another PR

small calibers still won't be effective vs PA thanks to no AP and low damage values, but this change makes them more than just literally useless (which is bad)

2023-11-11 13:47 UTC, maaacha requested changes
fix CI freaking out over armor and this can be merged

2023-11-11 15:34 UTC, ZephyrTFA commented on config/config.txt
> +ENABLE_LOCALHOST_RANK
```suggestion
# ENABLE_LOCALHOST_RANK
```

2023-11-11 15:34 UTC, ZephyrTFA approved these changes

2023-11-12 11:57 UTC, ZephyrTFA approved these changes

2023-11-12 11:57 UTC, merged